import { describe, expect, it } from 'vitest';
import {
  AI_SUMMARY_NOTICE,
  buildFinalizeSummaries,
  hasPublishableSummaries,
  type SummaryDrafts,
} from '../src/components/SubmissionWizard';

const longText = (label: string) =>
  `${label} `.repeat(18).trim() +
  ' with enough detail to pass the wizard summary length gate.';

describe('SubmissionWizard tiered summary payloads', () => {
  it('serializes every filled tier with its own text, AI flag, and model', () => {
    const drafts: SummaryDrafts = {
      school: {
        text: `  ${longText('School tier avoids jargon.')}  `,
        aiGenerated: true,
        aiModel: 'deepseek-v4-flash',
      },
      undergrad: {
        text: longText('Undergrad tier keeps method vocabulary.'),
        aiGenerated: true,
        aiModel: 'deepseek-v4-flash',
      },
      expert: {
        text: longText('Expert tier keeps assumptions and limitations.'),
        aiGenerated: true,
        aiModel: 'deepseek-v4-flash',
      },
    };

    expect(hasPublishableSummaries(drafts)).toBe(true);
    expect(buildFinalizeSummaries(drafts)).toEqual([
      {
        tier: 'school',
        text: longText('School tier avoids jargon.'),
        aiGenerated: true,
        aiModel: 'deepseek-v4-flash',
      },
      {
        tier: 'undergrad',
        text: longText('Undergrad tier keeps method vocabulary.'),
        aiGenerated: true,
        aiModel: 'deepseek-v4-flash',
      },
      {
        tier: 'expert',
        text: longText('Expert tier keeps assumptions and limitations.'),
        aiGenerated: true,
        aiModel: 'deepseek-v4-flash',
      },
    ]);
  });

  it('requires all generated summaries to carry visible AI mistake disclosure copy', () => {
    expect(AI_SUMMARY_NOTICE).toContain('Generated by AI');
    expect(AI_SUMMARY_NOTICE).toContain('AI can make mistakes');
  });
});
