import { useEffect, useRef, useState, type JSX } from 'react';
import { browserClient, type SummaryTier } from '../lib/api';

interface Props {
  paperId: string;
  initial?: Array<{
    tier: SummaryTier;
    text: string;
    aiGenerated: boolean;
    aiModel: string | null;
  }>;
}

const TIERS: SummaryTier[] = ['school', 'undergrad', 'expert'];

export function Explainer({ paperId, initial = [] }: Props): JSX.Element {
  const explainerRef = useRef<HTMLElement | null>(null);
  const [tier, setTier] = useState<SummaryTier>('undergrad');
  const [cache, setCache] = useState<
    Record<string, { text: string; aiGenerated: boolean; aiModel: string | null }>
  >(
    Object.fromEntries(
      initial.map((s) => [
        s.tier,
        { text: s.text, aiGenerated: s.aiGenerated, aiModel: s.aiModel },
      ]),
    ),
  );
  const [loading, setLoading] = useState<SummaryTier | null>(null);
  const [error, setError] = useState<string | null>(null);

  const current = cache[tier];
  const tabButtonStyle = {
    minHeight: 44,
    minWidth: 72,
    justifyContent: 'center',
  };

  useEffect(() => {
    if (!explainerRef.current) return;
    (window as Window & { openxivRenderMath?: (root?: ParentNode) => void }).openxivRenderMath?.(
      explainerRef.current,
    );
  }, [current?.text, tier]);

  async function explain(): Promise<void> {
    setLoading(tier);
    setError(null);
    try {
      const result = await browserClient().explain(paperId, tier);
      setCache((prev) => ({
        ...prev,
        [tier]: { text: result.text, aiGenerated: true, aiModel: result.model },
      }));
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setLoading(null);
    }
  }

  return (
    <section className="card" ref={explainerRef}>
      <div className="row" style={{ justifyContent: 'space-between', marginBottom: 12 }}>
        <strong>Explain at level</strong>
        <div className="row" role="tablist" style={{ flexWrap: 'wrap', gap: 8 }}>
          {TIERS.map((t) => (
            <button
              key={t}
              aria-selected={t === tier}
              className="btn"
              role="tab"
              style={
                t === tier
                  ? {
                      ...tabButtonStyle,
                      background: 'var(--accent)',
                      color: '#0e0e10',
                      borderColor: 'var(--accent)',
                    }
                  : tabButtonStyle
              }
              onClick={() => setTier(t)}
              type="button"
            >
              {t}
            </button>
          ))}
        </div>
      </div>
      {current ? (
        <>
          <p style={{ margin: 0, fontFamily: 'var(--font-serif)', lineHeight: 1.65 }}>
            {current.text}
          </p>
          {current.aiGenerated && (
            <div className="muted" style={{ marginTop: 8 }}>
              Generated by {current.aiModel ?? 'AI'} · cached
            </div>
          )}
        </>
      ) : (
        <button
          className="btn btn-primary"
          type="button"
          onClick={explain}
          disabled={loading !== null}
        >
          {loading === tier ? 'Asking…' : `Explain at ${tier}`}
        </button>
      )}
      {error && <p className="error">{error}</p>}
    </section>
  );
}
