import { useState, type JSX } from 'react';
import {
  SUBMISSION_TERMS_ATTESTATION,
  SUBMISSION_TERMS_LABEL,
  SUBMISSION_TERMS_VERSION,
} from '@openxiv/shared/submission-terms';

/**
 * ORCID normalizer. Inlined rather than imported from `@openxiv/shared`
 * because the shared package re-exports `ids.js`, which imports
 * `node:crypto` and breaks the Vite browser bundle. The canonical copy
 * lives in `packages/shared/src/licenses.ts` and is used by the
 * server-side schemas — keep both implementations in sync if you edit.
 */
function normalizeOrcid(input: string): string {
  return input
    .trim()
    .replace(/^https?:\/\//i, '')
    .replace(/^(?:www\.)?(?:sandbox\.)?orcid\.org\//i, '')
    .replace(/\/$/, '');
}
import { CategoryPicker, type CategoryNode } from './CategoryPicker';
import { SubmissionTerms } from './SubmissionTerms';

/**
 * Twitter conversion event id for "Paper submitted". Custom event at
 * X Ads — accepts only `conversion_id` per the dashboard schema.
 * Sourced from build-time env; hardcoded fallback matches the launch
 * config so a missing env var doesn't silently skip tracking.
 */
const PAPER_SUBMIT_EVENT_ID =
  (import.meta.env.PUBLIC_TWITTER_PAPERSUBMIT_EVENT_ID as string | undefined) ?? 'tw-rch4y-rch5e';

/**
 * Structured rejection payload emitted by the intake API. Mirrors
 * `apps/api/src/services/error-messages.ts:UserErrorPayload`. The
 * `details` map carries scenario-specific info (e.g. `missing_files`
 * for `companions_required`, `files` for `multiple_documentclass`).
 */
interface UserErrorPayloadShape {
  error_code: string;
  user_message: {
    title: string;
    body: string;
    fix_hint: string;
  };
  details?: Record<string, unknown>;
}

/**
 * Render a structured rejection. Used in the upload step in place of
 * the raw error string when the server emits a `user_message` payload.
 */
function RejectionBox({ payload }: { payload: UserErrorPayloadShape }): JSX.Element {
  const details = payload.details ?? {};
  const missing =
    Array.isArray(details['missing_files']) && (details['missing_files'] as unknown[]).every((x) => typeof x === 'string')
      ? (details['missing_files'] as string[])
      : null;
  const multipleEntries =
    Array.isArray(details['files']) && (details['files'] as unknown[]).every((x) => typeof x === 'string')
      ? (details['files'] as string[])
      : null;
  return (
    <article
      className="card"
      role="alert"
      style={{
        borderColor: 'var(--tone-caution)',
        padding: '14px 16px',
        marginTop: 12,
      }}
    >
      <strong style={{ fontFamily: 'var(--font-serif)', fontSize: 16 }}>
        {payload.user_message.title}
      </strong>
      <p style={{ margin: '8px 0 6px', lineHeight: 1.5 }}>{payload.user_message.body}</p>
      <p className="muted" style={{ margin: '0 0 8px', fontSize: 13 }}>
        {payload.user_message.fix_hint}
      </p>
      {missing && missing.length > 0 && (
        <div style={{ marginTop: 8 }}>
          <div className="muted" style={{ fontSize: 12, marginBottom: 4 }}>Missing files:</div>
          <ul style={{ margin: 0, paddingLeft: 18, fontSize: 13 }}>
            {missing.slice(0, 20).map((m) => (
              <li key={m}><code>{m}</code></li>
            ))}
            {missing.length > 20 && <li className="muted">…and {missing.length - 20} more</li>}
          </ul>
        </div>
      )}
      {multipleEntries && multipleEntries.length > 0 && (
        <div style={{ marginTop: 8 }}>
          <div className="muted" style={{ fontSize: 12, marginBottom: 4 }}>Detected manuscripts:</div>
          <ul style={{ margin: 0, paddingLeft: 18, fontSize: 13 }}>
            {multipleEntries.map((m) => (
              <li key={m}><code>{m}</code></li>
            ))}
          </ul>
        </div>
      )}
    </article>
  );
}

type DisclosureLevel = 'none' | 'assistant' | 'coauthor' | 'primary';
export const SUMMARY_TIERS = ['school', 'undergrad', 'expert'] as const;
type Tier = (typeof SUMMARY_TIERS)[number];
export const AI_SUMMARY_NOTICE =
  'Generated by AI. AI can make mistakes. Review before publishing.';

export interface SummaryDraft {
  text: string;
  aiGenerated: boolean;
  aiModel: string | null;
}

export type SummaryDrafts = Record<Tier, SummaryDraft>;

export function createEmptySummaryDrafts(): SummaryDrafts {
  return {
    school: { text: '', aiGenerated: false, aiModel: null },
    undergrad: { text: '', aiGenerated: false, aiModel: null },
    expert: { text: '', aiGenerated: false, aiModel: null },
  };
}

export function buildFinalizeSummaries(summaries: SummaryDrafts): Array<{
  tier: Tier;
  text: string;
  aiGenerated: boolean;
  aiModel?: string;
}> {
  return SUMMARY_TIERS.map((tier) => {
    const draft = summaries[tier];
    return {
      tier,
      text: draft.text.trim(),
      aiGenerated: draft.aiGenerated,
      ...(draft.aiModel ? { aiModel: draft.aiModel } : {}),
    };
  }).filter((summary) => summary.text.length > 0);
}

export function hasPublishableSummaries(summaries: SummaryDrafts): boolean {
  const filled = buildFinalizeSummaries(summaries);
  return (
    filled.length > 0 &&
    filled.every((summary) => summary.text.length >= 80 && summary.text.length <= 4000)
  );
}

function hasAiGeneratedSummary(summaries: SummaryDrafts): boolean {
  return buildFinalizeSummaries(summaries).some((summary) => summary.aiGenerated);
}

function mergeModelNames(existing: string, additions: Array<string | null | undefined>): string {
  const names = new Set(
    existing
      .split(',')
      .map((s) => s.trim())
      .filter(Boolean),
  );
  for (const addition of additions) {
    if (addition?.trim()) names.add(addition.trim());
  }
  return Array.from(names).join(', ');
}

function ensureSummaryDisclosure(
  disclosure: WizardForm['disclosure'],
  aiModel?: string | null,
): WizardForm['disclosure'] {
  return {
    ...disclosure,
    level: disclosure.level === 'none' ? 'assistant' : disclosure.level,
    aiUsed: disclosure.aiUsed.includes('summary')
      ? disclosure.aiUsed
      : [...disclosure.aiUsed, 'summary'],
    models: mergeModelNames(disclosure.models, [aiModel]),
  };
}

interface ExtractedAuthor {
  displayName: string;
  orcid?: string;
  affiliation?: string;
}

interface IntakeResponse {
  sessionId: string;
  previewPdfUrl: string | null;
  extractedTitle: string | null;
  extractedAbstract: string | null;
  extractedAuthors: ExtractedAuthor[];
  suggestedKeywords: string[];
  grobidFailed: boolean;
  sha256: string;
  sizeBytes: number;
  compileLogTail: string;
}

interface AuthorRow {
  displayName: string;
  affiliation: string;
  orcid: string;
  isCorresponding: boolean;
}

interface WizardForm {
  title: string;
  abstract: string;
  primaryCategory: string;
  /**
   * Up to 2 cross-listing categories beyond `primaryCategory`. The picker
   * enforces the cap visually; the API re-validates server-side and
   * rejects payloads that bypassed the UI.
   */
  secondaryCategories: string[];
  license: string;
  authors: AuthorRow[];
  keywords: string;
  summaries: SummaryDrafts;
  disclosure: {
    level: DisclosureLevel;
    aiUsed: string[];
    models: string;
    notes: string;
  };
}

const MAX_CROSS_LISTINGS = 2;

const AI_USE_OPTIONS = ['ideation', 'literature', 'derivation', 'code', 'writing', 'figures', 'summary', 'translation'];
const LICENSES = [
  'CC-BY-4.0',
  'CC-BY-SA-4.0',
  'CC-BY-NC-4.0',
  'CC-BY-NC-SA-4.0',
  'CC-BY-ND-4.0',
  'CC0-1.0',
  'arXiv-nonexclusive-distrib',
  'all-rights-reserved',
];

interface Props {
  categories: Array<{ code: string; name: string; group: string }>;
  /**
   * Server-rendered profile of the signed-in user. We use it to prefill
   * the first author row so a submitter with a linked ORCID does not
   * have to type their own name or paste their own iD. Null when the
   * page rendered for an unauthenticated viewer (the route should have
   * redirected to sign-in, but we guard anyway).
   */
  viewer?: { displayName: string; orcid: string | null } | null;
}

export function SubmissionWizard({ categories, viewer }: Props): JSX.Element {
  // 6-step wizard:
  //   1 Subject  →  2 Upload  →  3 Title  →  4 Authors  →  5 Summary  →  6 Publish
  // Subject moved to the front so a chemistry/biology submitter sees we
  // support them BEFORE they spend time compiling a paper they thought
  // wouldn't fit.
  const [step, setStep] = useState<1 | 2 | 3 | 4 | 5 | 6>(1);
  const [intake, setIntake] = useState<IntakeResponse | null>(null);
  const [intakeError, setIntakeError] = useState<string | null>(null);
  const [intakeUserError, setIntakeUserError] = useState<UserErrorPayloadShape | null>(null);
  const [intakeWorking, setIntakeWorking] = useState(false);

  const [form, setForm] = useState<WizardForm>({
    title: '',
    abstract: '',
    // Empty = forces the user to pick consciously in Step1Subject. The
    // server-side zod schema rejects empty strings, so we cannot ship a
    // paper without an explicit category.
    primaryCategory: '',
    secondaryCategories: [],
    license: 'CC-BY-4.0',
    // Prefill the first author from the signed-in viewer when we have
    // a profile available. ORCID is stored bare here even though the
    // wizard accepts both URL and bare forms in the input. applyIntake
    // overrides authors when the LaTeX bundle declares its own list.
    authors: [
      {
        displayName: viewer?.displayName ?? '',
        affiliation: '',
        orcid: viewer?.orcid ?? '',
        isCorresponding: true,
      },
    ],
    keywords: '',
    summaries: createEmptySummaryDrafts(),
    disclosure: { level: 'none', aiUsed: [], models: '', notes: '' },
  });
  const [activeSummaryTier, setActiveSummaryTier] = useState<Tier>('undergrad');
  const [suggestWorkingTier, setSuggestWorkingTier] = useState<Tier | null>(null);
  const [suggestError, setSuggestError] = useState<string | null>(null);
  const [publishError, setPublishError] = useState<string | null>(null);
  const [publishing, setPublishing] = useState(false);
  const [publishedPaperId, setPublishedPaperId] = useState<string | null>(null);
  const [termsAccepted, setTermsAccepted] = useState(false);
  const [termsModalOpen, setTermsModalOpen] = useState(false);

  function update<K extends keyof WizardForm>(key: K, value: WizardForm[K]): void {
    setForm((prev) => ({ ...prev, [key]: value }));
  }

  function applyIntake(intake: IntakeResponse): void {
    setForm((prev) => ({
      ...prev,
      title: intake.extractedTitle ?? prev.title,
      abstract: intake.extractedAbstract ?? prev.abstract,
      authors:
        intake.extractedAuthors.length > 0
          ? intake.extractedAuthors.map((a, i) => ({
              displayName: a.displayName,
              affiliation: a.affiliation ?? '',
              orcid: a.orcid ?? '',
              isCorresponding: i === 0,
            }))
          : prev.authors,
      keywords: intake.suggestedKeywords.join(', '),
    }));
  }

  async function uploadIntake(file: File): Promise<void> {
    setIntakeWorking(true);
    setIntakeError(null);
    setIntakeUserError(null);
    try {
      const body = new FormData();
      body.append('source', file, file.name);
      const res = await fetch('/api-proxy/submissions/intake', {
        method: 'POST',
        body,
        credentials: 'include',
      });
      if (!res.ok) {
        // Structured rejection: the server emits
        //   { error_code, user_message: {title, body, fix_hint}, details? }
        // for everything the pre-flight gate catches (no_documentclass,
        // multiple_documentclass, companions_required, malformed_archive,
        // size_limit). Render the human-readable surface; never expose
        // the bare error_code string to the user.
        const payload = await res
          .json()
          .catch(() => ({} as Record<string, unknown>));
        if (payload && typeof payload === 'object' && 'user_message' in payload) {
          setIntakeUserError(payload as UserErrorPayloadShape);
          return;
        }
        const detail = JSON.stringify(payload).slice(0, 300);
        throw new Error(`${res.status}: ${detail}`);
      }
      const data = (await res.json()) as IntakeResponse;
      setIntake(data);
      applyIntake(data);
      setStep(2);
    } catch (err) {
      setIntakeError((err as Error).message);
    } finally {
      setIntakeWorking(false);
    }
  }

  async function suggestSummary(): Promise<void> {
    if (!intake) return;
    const tier = activeSummaryTier;
    setSuggestWorkingTier(tier);
    setSuggestError(null);
    try {
      const res = await fetch('/api-proxy/summaries/suggest', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        credentials: 'include',
        body: JSON.stringify({ sessionId: intake.sessionId, tier }),
      });
      if (!res.ok) {
        const detail = await res.text().catch(() => '');
        throw new Error(`${res.status}: ${detail.slice(0, 300)}`);
      }
      const data = (await res.json()) as { text: string; aiModel: string };
      setForm((prev) => ({
        ...prev,
        summaries: {
          ...prev.summaries,
          [tier]: { text: data.text, aiGenerated: true, aiModel: data.aiModel },
        },
        disclosure: ensureSummaryDisclosure(prev.disclosure, data.aiModel),
      }));
    } catch (err) {
      setSuggestError((err as Error).message);
    } finally {
      setSuggestWorkingTier(null);
    }
  }

  async function publish(): Promise<void> {
    if (!intake) return;
    if (!termsAccepted) {
      setPublishError('You must accept the submission terms before publishing.');
      return;
    }
    setPublishing(true);
    setPublishError(null);
    try {
      const summaries = buildFinalizeSummaries(form.summaries);
      const summaryAiGenerated = summaries.some((summary) => summary.aiGenerated);
      const disclosureModels = mergeModelNames(
        form.disclosure.models,
        summaries.map((summary) => summary.aiModel),
      );
      const disclosureLevel =
        summaryAiGenerated && form.disclosure.level === 'none'
          ? 'assistant'
          : form.disclosure.level;
      const disclosureAiUsed =
        summaryAiGenerated && !form.disclosure.aiUsed.includes('summary')
          ? [...form.disclosure.aiUsed, 'summary']
          : form.disclosure.aiUsed;
      const body = {
        sessionId: intake.sessionId,
        title: form.title.trim(),
        abstract: form.abstract.trim(),
        license: form.license,
        primaryCategory: form.primaryCategory,
        // Send `crossListings` (canonical); the API also accepts the
        // legacy `secondaryCategories` alias for backward-compat with
        // stale browser caches. We send both with the same value so a
        // stack mid-rollout never sees a divergence.
        crossListings: form.secondaryCategories,
        secondaryCategories: form.secondaryCategories,
        authors: form.authors
          .filter((a) => a.displayName.trim().length > 0)
          .map((a) => {
            // Strip orcid.org URL prefix so users can paste either the
            // bare 0000-0000-0000-000X form or the full profile URL.
            const orcidNorm = normalizeOrcid(a.orcid);
            return {
              displayName: a.displayName.trim(),
              ...(orcidNorm ? { orcid: orcidNorm } : {}),
              ...(a.affiliation.trim() ? { affiliation: a.affiliation.trim() } : {}),
              isCorresponding: a.isCorresponding,
            };
          }),
        keywords: form.keywords
          .split(',')
          .map((s) => s.trim())
          .filter(Boolean),
        disclosure: {
          level: disclosureLevel,
          aiUsed: disclosureAiUsed,
          models: disclosureModels
            .split(',')
            .map((s) => s.trim())
            .filter(Boolean)
            .map((name) => ({ name })),
          ...(form.disclosure.notes.trim() ? { notes: form.disclosure.notes.trim() } : {}),
          summaryAiGenerated,
          attestation: 'i-attest-this-disclosure-is-accurate' as const,
        },
        summaries,
        ...(summaries[0] ? { summary: summaries[0] } : {}),
        submissionTerms: {
          version: SUBMISSION_TERMS_VERSION,
          attestation: SUBMISSION_TERMS_ATTESTATION,
        },
      };
      const res = await fetch('/api-proxy/submissions/finalize', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        credentials: 'include',
        body: JSON.stringify(body),
      });
      if (!res.ok) {
        const detail = await res.text().catch(() => '');
        throw new Error(`${res.status}: ${detail.slice(0, 300)}`);
      }
      const data = (await res.json()) as { paperId: string };
      setPublishedPaperId(data.paperId);
      try {
        const tracker = (typeof window !== 'undefined' ? window : undefined) as
          | (Window & {
              openxivTrack?: (
                eventType: string,
                targetUri: string,
                targetType: string,
                context?: Record<string, unknown>,
              ) => void;
            })
          | undefined;
        tracker?.openxivTrack?.('submit_complete', data.paperId, 'submission', {
          primaryCategory: form.primaryCategory,
        });
      } catch {
        // never throw out of a fire
      }
      // Twitter Pixel PaperSubmitted fire. The helper is consent-gated,
      // DNT-gated, and debounced; we always call it. Custom events at
      // X Ads accept only `conversion_id` (no Value / Contents fields
      // per the rch5e event configuration in the dashboard).
      try {
        const tw = (typeof window !== 'undefined' ? window : undefined) as
          | (Window & { openxivTwitter?: { event(id: string, params: Record<string, unknown>): void } })
          | undefined;
        if (tw?.openxivTwitter) {
          tw.openxivTwitter.event(PAPER_SUBMIT_EVENT_ID, {
            conversion_id:
              typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function'
                ? crypto.randomUUID()
                : `${Date.now()}-${Math.random().toString(36).slice(2, 10)}`,
          });
        }
      } catch {
        // never throw out of a fire
      }
    } catch (err) {
      setPublishError((err as Error).message);
    } finally {
      setPublishing(false);
    }
  }

  if (publishedPaperId) {
    return (
      <div className="card">
        <h2 style={{ marginTop: 0 }}>Submitted ✓</h2>
        <p>The publish saga is running. Once the openxiv id is allocated you'll be redirected automatically.</p>
        <p>
          <a className="btn btn-primary" href={`/paper/${publishedPaperId}`}>Open paper</a>
        </p>
        <p className="muted">Saga stages happen in order: S3 id_assigned → S4 pds_paper → S5 pds_summary_disclosure → S6 bluesky_bridge.</p>
      </div>
    );
  }

  return (
    <div className="stack">
      <Stepper
        step={step}
        total={6}
        labels={['Subject', 'Upload', 'Title', 'Authors', 'Summary', 'Publish']}
      />

      {step === 1 && (
        <Step1Subject
          categories={categories}
          value={form.primaryCategory}
          crossListings={form.secondaryCategories}
          onChangePrimary={(code) => {
            // Replacing the primary may invalidate a previously-picked
            // secondary that happens to equal the new primary. Drop any
            // such overlap immediately rather than letting the server
            // 400 on submit.
            update('primaryCategory', code);
            setForm((prev) => ({
              ...prev,
              primaryCategory: code,
              secondaryCategories: prev.secondaryCategories.filter((c) => c !== code),
            }));
          }}
          onChangeCrossListings={(codes) => update('secondaryCategories', codes)}
          onNext={() => setStep(2)}
        />
      )}

      {step === 2 && (
        <Step2Upload
          working={intakeWorking}
          error={intakeError}
          userError={intakeUserError}
          intake={intake}
          onPick={uploadIntake}
          onBack={() => setStep(1)}
          onContinue={() => setStep(3)}
        />
      )}

      {step === 3 && intake && (
        <Step3TitleAbstract
          form={form}
          intake={intake}
          onChange={update}
          onBack={() => setStep(2)}
          onNext={() => setStep(4)}
        />
      )}

      {step === 4 && intake && (
        <Step4Authors
          form={form}
          categories={categories}
          onChange={update}
          onBack={() => setStep(3)}
          onNext={() => setStep(5)}
        />
      )}

      {step === 5 && intake && (
        <Step5SummaryDisclosure
          form={form}
          activeTier={activeSummaryTier}
          onChangeActiveTier={setActiveSummaryTier}
          onChange={update}
          onSuggest={suggestSummary}
          suggestingTier={suggestWorkingTier}
          suggestError={suggestError}
          onBack={() => setStep(4)}
          onNext={() => setStep(6)}
        />
      )}

      {step === 6 && intake && (
        <Step6Preview
          form={form}
          intake={intake}
          publishing={publishing}
          error={publishError}
          termsAccepted={termsAccepted}
          onOpenTerms={() => setTermsModalOpen(true)}
          onToggleTerms={(v) => {
            if (!termsAccepted) {
              setTermsModalOpen(true);
            } else {
              setTermsAccepted(v);
            }
          }}
          onBack={() => setStep(5)}
          onPublish={publish}
        />
      )}

      <SubmissionTerms
        open={termsModalOpen}
        acceptedAlready={termsAccepted}
        onClose={() => setTermsModalOpen(false)}
        onAccept={() => {
          setTermsAccepted(true);
          setTermsModalOpen(false);
        }}
      />
    </div>
  );
}

function Stepper({ step, total, labels }: { step: number; total: number; labels: string[] }): JSX.Element {
  return (
    <div className="row" style={{ gap: 8, flexWrap: 'wrap' }}>
      {labels.map((label, i) => {
        const idx = i + 1;
        const isActive = idx === step;
        const isDone = idx < step;
        return (
          <div
            key={label}
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: 6,
              padding: '6px 12px',
              borderRadius: 999,
              border: `1px solid ${isActive ? 'var(--accent)' : 'var(--border)'}`,
              background: isDone ? 'rgba(122,167,240,0.08)' : isActive ? 'rgba(122,167,240,0.18)' : 'transparent',
              color: isActive || isDone ? 'var(--text-primary)' : 'var(--text-secondary)',
              fontSize: 13,
            }}
          >
            <span style={{ fontVariantNumeric: 'tabular-nums', opacity: 0.8 }}>
              {isDone ? '✓' : idx}
            </span>
            <span>{label}</span>
          </div>
        );
      })}
      <span className="muted" style={{ marginLeft: 'auto' }}>
        Step {step} / {total}
      </span>
    </div>
  );
}

function Step1Subject({
  categories,
  value,
  crossListings,
  onChangePrimary,
  onChangeCrossListings,
  onNext,
}: {
  categories: CategoryNode[];
  value: string;
  crossListings: string[];
  onChangePrimary: (code: string) => void;
  onChangeCrossListings: (codes: string[]) => void;
  onNext: () => void;
}): JSX.Element {
  return (
    <section className="stack">
      <h2 style={{ margin: 0, fontFamily: 'var(--font-serif)' }}>Pick a primary subject</h2>
      <p className="muted" style={{ marginTop: -8 }}>
        We accept submissions across every STEM and humanities discipline. Pick the closest
        match. Your paper will appear in this category's feed, plus up to two cross-listed
        feeds (added below).
      </p>
      <CategoryPicker
        categories={categories}
        mode="single"
        value={value}
        onChange={onChangePrimary}
      />

      {value && (
        <details className="card" style={{ marginTop: 8 }} open={crossListings.length > 0}>
          <summary style={{ cursor: 'pointer', fontFamily: 'var(--font-serif)', fontSize: 16 }}>
            Cross-list to up to {MAX_CROSS_LISTINGS} secondary subjects (optional)
          </summary>
          <p className="muted" style={{ fontSize: 13, marginTop: 8 }}>
            Your paper will appear in the primary feed plus the cross-listed feeds.
            Pick the secondary subjects that genuinely apply — readers there will see
            it as a cross-post, not as off-topic noise.
          </p>
          <CategoryPicker
            categories={categories}
            mode="multi-with-cap"
            max={MAX_CROSS_LISTINGS}
            value={crossListings}
            excludeCodes={[value]}
            onChange={onChangeCrossListings}
          />
        </details>
      )}

      <div className="row" style={{ justifyContent: 'space-between', marginTop: 8 }}>
        <span className="muted" style={{ fontSize: 12 }}>
          Don't see your field? Email <a href="mailto:davidich.alfyorov@gmail.com"><code>davidich.alfyorov@gmail.com</code></a> and we'll add it.
        </span>
        <button
          type="button"
          className="btn btn-primary"
          onClick={onNext}
          disabled={!value || crossListings.length > MAX_CROSS_LISTINGS}
          title={
            !value
              ? 'Pick a subject to continue'
              : crossListings.length > MAX_CROSS_LISTINGS
                ? `Remove a cross-listing — maximum is ${MAX_CROSS_LISTINGS}`
                : undefined
          }
        >
          Continue to upload →
        </button>
      </div>
    </section>
  );
}

function Step2Upload({
  working,
  error,
  userError,
  intake,
  onPick,
  onBack,
  onContinue,
}: {
  working: boolean;
  error: string | null;
  userError: UserErrorPayloadShape | null;
  intake: IntakeResponse | null;
  onPick: (file: File) => Promise<void>;
  onBack: () => void;
  onContinue: () => void;
}): JSX.Element {
  const [dragOver, setDragOver] = useState(false);
  return (
    <section className="stack">
      <h2 style={{ margin: 0, fontFamily: 'var(--font-serif)' }}>Drop your paper source</h2>
      <p className="muted" style={{ marginTop: -8 }}>
        {/* DISABLED 2026-05 PDF upload; revert when GROBID+Nougat pipeline lands */}
        LaTeX source — <code>.tex</code> or <code>.tar.gz</code> / <code>.zip</code>
        bundle (must contain a top-level <code>.tex</code> + figures, bib).
        We compile with Tectonic, render with LaTeXML, and extract metadata.
      </p>
      <p
        className="muted"
        style={{
          marginTop: -4,
          padding: '8px 12px',
          background: 'var(--bg-elev)',
          border: '1px solid var(--border)',
          borderRadius: 6,
          fontSize: 13,
        }}
      >
        PDF-only uploads are temporarily disabled. We need the LaTeX
        source to produce the HTML view, math rendering, figure
        extraction, and the per-paper marker that ties the published
        record back to its OpenXiv id.
      </p>
      <div className="row" style={{ justifyContent: 'flex-start' }}>
        <button type="button" className="btn btn-sm" onClick={onBack} disabled={working}>
          ← Back to subject
        </button>
      </div>

      <div
        onDragOver={(e) => {
          e.preventDefault();
          setDragOver(true);
        }}
        onDragLeave={() => setDragOver(false)}
        onDrop={(e) => {
          e.preventDefault();
          setDragOver(false);
          const file = e.dataTransfer.files?.[0];
          if (file) void onPick(file);
        }}
        style={{
          border: `2px dashed ${dragOver ? 'var(--accent)' : 'var(--border)'}`,
          borderRadius: 14,
          padding: '40px 24px',
          textAlign: 'center',
          background: dragOver ? 'rgba(122,167,240,0.06)' : 'var(--bg-elev)',
        }}
      >
        {working ? (
          <>
            <div style={{ fontSize: 16, marginBottom: 8 }}>Compiling and extracting metadata…</div>
            <div className="muted">Tectonic → GROBID → keyword extraction.</div>
          </>
        ) : (
          <>
            <div style={{ fontSize: 16, marginBottom: 8 }}>Drag a file here, or</div>
            <label className="btn btn-primary">
              Choose file
              {/*
                DISABLED 2026-05 PDF upload; revert when GROBID+Nougat
                pipeline lands. The previous `accept` value listed
                `.pdf,application/pdf` alongside the source archives;
                stripped here so the OS picker only offers source files.
              */}
              <input
                type="file"
                style={{ display: 'none' }}
                accept=".tex,.tar.gz,.tgz,.zip,application/gzip,application/zip,application/x-tar,text/x-tex"
                onChange={(e) => {
                  const file = e.target.files?.[0];
                  if (file) void onPick(file);
                }}
              />
            </label>
          </>
        )}
      </div>

      {userError && <RejectionBox payload={userError} />}
      {/*
        `error` is the bare network/transport message; user-facing
        rejections come through `userError` and render structured.
        Show the raw string only when no structured payload exists.
      */}
      {!userError && error && <p className="error">{error}</p>}

      {intake && !working && (
        <div className="card">
          <strong>Intake complete.</strong>
          <ul className="muted" style={{ margin: '8px 0', paddingLeft: 20 }}>
            <li>Title: {intake.extractedTitle ?? <em>not detected — you'll enter manually</em>}</li>
            <li>Authors: {intake.extractedAuthors.length > 0 ? intake.extractedAuthors.map((a) => a.displayName).join(', ') : <em>none detected</em>}</li>
            <li>Suggested keywords: {intake.suggestedKeywords.join(', ') || <em>none</em>}</li>
            <li>SHA-256: <code>{intake.sha256.slice(0, 16)}…</code> · {(intake.sizeBytes / 1024).toFixed(1)} KB</li>
            {intake.grobidFailed && <li><strong>GROBID extraction failed; falling back to manual entry.</strong></li>}
          </ul>
          {intake.previewPdfUrl && (
            <iframe
              src={intake.previewPdfUrl}
              title="Preview"
              style={{ width: '100%', height: 360, border: '1px solid var(--border)', borderRadius: 8, background: '#0a0a0c' }}
            />
          )}
          <div className="row" style={{ justifyContent: 'flex-end', marginTop: 12 }}>
            <button className="btn btn-primary" type="button" onClick={onContinue}>
              Continue to title & abstract
            </button>
          </div>
        </div>
      )}
    </section>
  );
}

function Step3TitleAbstract({
  form,
  intake,
  onChange,
  onBack,
  onNext,
}: {
  form: WizardForm;
  intake: IntakeResponse;
  onChange: <K extends keyof WizardForm>(k: K, v: WizardForm[K]) => void;
  onBack: () => void;
  onNext: () => void;
}): JSX.Element {
  const titleAutofilled = intake.extractedTitle === form.title && form.title.length > 0;
  const abstractAutofilled = intake.extractedAbstract === form.abstract && form.abstract.length > 0;
  return (
    <section className="stack">
      <h2 style={{ margin: 0, fontFamily: 'var(--font-serif)' }}>Title & abstract</h2>
      <p className="muted" style={{ marginTop: -8 }}>
        Auto-filled from your upload — edit anything that looks off.
      </p>
      <div>
        <label className="field-label">
          Title
          {titleAutofilled && <span className="muted"> · auto-filled from GROBID</span>}
        </label>
        <input
          className="input"
          value={form.title}
          onChange={(e) => onChange('title', e.target.value)}
        />
      </div>
      <div>
        <label className="field-label">
          Abstract
          {abstractAutofilled && <span className="muted"> · auto-filled from GROBID</span>}
        </label>
        <textarea
          className="textarea"
          rows={8}
          value={form.abstract}
          onChange={(e) => onChange('abstract', e.target.value)}
        />
      </div>
      <Nav onBack={onBack} onNext={onNext} nextDisabled={form.title.trim().length < 4} />
    </section>
  );
}

function Step4Authors({
  form,
  categories,
  onChange,
  onBack,
  onNext,
}: {
  form: WizardForm;
  categories: Array<{ code: string; name: string; group: string }>;
  onChange: <K extends keyof WizardForm>(k: K, v: WizardForm[K]) => void;
  onBack: () => void;
  onNext: () => void;
}): JSX.Element {
  function setAuthor(idx: number, patch: Partial<AuthorRow>): void {
    onChange(
      'authors',
      form.authors.map((a, i) => (i === idx ? { ...a, ...patch } : a)),
    );
  }
  return (
    <section className="stack">
      <h2 style={{ margin: 0, fontFamily: 'var(--font-serif)' }}>Authors, license & keywords</h2>

      <div>
        <label className="field-label">Authors</label>
        <div className="stack-sm">
          {form.authors.map((a, idx) => (
            <div key={idx} className="row" style={{ gap: 8, alignItems: 'flex-start' }}>
              <input
                className="input"
                placeholder="Display name"
                value={a.displayName}
                onChange={(e) => setAuthor(idx, { displayName: e.target.value })}
                style={{ flex: 2 }}
              />
              <input
                className="input"
                placeholder="Affiliation"
                value={a.affiliation}
                onChange={(e) => setAuthor(idx, { affiliation: e.target.value })}
                style={{ flex: 2 }}
              />
              <input
                className="input"
                placeholder="ORCID — bare ID or URL (optional)"
                value={a.orcid}
                onChange={(e) => setAuthor(idx, { orcid: e.target.value })}
                onBlur={(e) => {
                  // Normalize on blur so the visible field matches what
                  // we send to the API. Pasting the full profile URL
                  // from orcid.org collapses to the bare iD here.
                  const trimmed = normalizeOrcid(e.target.value);
                  if (trimmed !== a.orcid) setAuthor(idx, { orcid: trimmed });
                }}
                style={{ flex: 1.4 }}
              />
              <label className="row" style={{ gap: 4, fontSize: 13, alignItems: 'center', whiteSpace: 'nowrap' }}>
                <input
                  type="radio"
                  name="corresponding"
                  checked={a.isCorresponding}
                  onChange={() =>
                    onChange(
                      'authors',
                      form.authors.map((x, i) => ({ ...x, isCorresponding: i === idx })),
                    )
                  }
                />
                <span>corresponding</span>
              </label>
              <button
                type="button"
                className="btn"
                disabled={form.authors.length === 1}
                onClick={() =>
                  onChange(
                    'authors',
                    form.authors.filter((_, i) => i !== idx),
                  )
                }
                title="Remove author"
              >
                ✕
              </button>
            </div>
          ))}
          <button
            type="button"
            className="btn"
            onClick={() =>
              onChange('authors', [
                ...form.authors,
                { displayName: '', affiliation: '', orcid: '', isCorresponding: false },
              ])
            }
          >
            + add author
          </button>
        </div>
      </div>

      <div className="muted" style={{ fontSize: 13 }}>
        Primary subject: <strong style={{ color: 'var(--text-primary)' }}>{form.primaryCategory || '—'}</strong>
        {form.primaryCategory && categories.find((c) => c.code === form.primaryCategory) && (
          <>
            {' '}— {categories.find((c) => c.code === form.primaryCategory)!.name}
            <span> · </span>
            {categories.find((c) => c.code === form.primaryCategory)!.group}
          </>
        )}
        <span> · </span>
        <a href="#" onClick={(e) => { e.preventDefault(); window.scrollTo({ top: 0, behavior: 'smooth' }); }}>
          Change in step 1
        </a>
      </div>

      <div className="muted" style={{ fontSize: 13 }}>
        Cross-listed to:{' '}
        {form.secondaryCategories.length === 0 ? (
          <em>none</em>
        ) : (
          form.secondaryCategories.map((code, i) => (
            <span key={code}>
              {i > 0 ? ', ' : ''}
              <code>{code}</code>
            </span>
          ))
        )}
        <span> · </span>
        <a
          href="#"
          onClick={(e) => {
            e.preventDefault();
            window.scrollTo({ top: 0, behavior: 'smooth' });
          }}
        >
          Change in step 1
        </a>
      </div>

      <div>
        <label className="field-label">License</label>
        <select
          className="select"
          value={form.license}
          onChange={(e) => onChange('license', e.target.value)}
        >
          {LICENSES.map((l) => (
            <option key={l} value={l}>
              {l}
            </option>
          ))}
        </select>
      </div>

      <div>
        <label className="field-label">Keywords (comma-separated; pre-filled from extraction)</label>
        <input
          className="input"
          value={form.keywords}
          onChange={(e) => onChange('keywords', e.target.value)}
        />
      </div>

      <Nav
        onBack={onBack}
        onNext={onNext}
        nextDisabled={
          form.authors.filter((a) => a.displayName.trim()).length === 0 || !form.primaryCategory
        }
      />
    </section>
  );
}

function Step5SummaryDisclosure({
  form,
  activeTier,
  onChangeActiveTier,
  onChange,
  onSuggest,
  suggestingTier,
  suggestError,
  onBack,
  onNext,
}: {
  form: WizardForm;
  activeTier: Tier;
  onChangeActiveTier: (tier: Tier) => void;
  onChange: <K extends keyof WizardForm>(k: K, v: WizardForm[K]) => void;
  onSuggest: () => Promise<void>;
  suggestingTier: Tier | null;
  suggestError: string | null;
  onBack: () => void;
  onNext: () => void;
}): JSX.Element {
  function toggleAiUse(option: string): void {
    onChange('disclosure', {
      ...form.disclosure,
      aiUsed: form.disclosure.aiUsed.includes(option)
        ? form.disclosure.aiUsed.filter((x) => x !== option)
        : [...form.disclosure.aiUsed, option],
    });
  }

  const currentSummary = form.summaries[activeTier];
  const anySummaryAiGenerated = hasAiGeneratedSummary(form.summaries);
  const disclosureInvalid =
    (form.disclosure.level !== 'none' &&
      (form.disclosure.aiUsed.length === 0 || form.disclosure.models.trim().length === 0)) ||
    (anySummaryAiGenerated &&
      (form.disclosure.level === 'none' ||
        !form.disclosure.aiUsed.includes('summary') ||
        form.disclosure.models.trim().length === 0));
  const summaryInvalid = !hasPublishableSummaries(form.summaries);

  function setCurrentSummary(patch: Partial<SummaryDraft>): void {
    onChange('summaries', {
      ...form.summaries,
      [activeTier]: { ...currentSummary, ...patch },
    });
  }

  function tierOptionLabel(tier: Tier): string {
    const draft = form.summaries[tier];
    if (!draft.text.trim()) return tier;
    return `${tier} (${draft.aiGenerated ? 'AI' : 'draft'})`;
  }

  return (
    <section className="stack">
      <h2 style={{ margin: 0, fontFamily: 'var(--font-serif)' }}>Plain-language summary & AI disclosure</h2>

      <div>
        <label className="field-label">Plain summary tier</label>
        <select
          className="select"
          value={activeTier}
          disabled={suggestingTier !== null}
          onChange={(e) => onChangeActiveTier(e.target.value as Tier)}
        >
          {SUMMARY_TIERS.map((tier) => (
            <option key={tier} value={tier}>
              {tierOptionLabel(tier)}
            </option>
          ))}
        </select>
        <p className="muted" style={{ margin: '6px 0 0', fontSize: 13 }}>
          At least one plain-language summary tier is required. The other tiers are optional, recommended.
        </p>
      </div>

      <div>
        <label className="field-label">
          Plain-language summary (80–4000 chars; fill at least one tier)
        </label>
        <textarea
          className="textarea"
          rows={8}
          value={currentSummary.text}
          onChange={(e) =>
            setCurrentSummary({ text: e.target.value, aiGenerated: false, aiModel: null })
          }
          placeholder="Explain the paper to someone at your chosen tier."
        />
        <div className="row" style={{ gap: 12, marginTop: 8 }}>
          <button
            type="button"
            className="btn"
            onClick={onSuggest}
            disabled={suggestingTier !== null}
          >
            {suggestingTier === activeTier ? 'Drafting summary...' : 'Suggest summary'}
          </button>
          <label className="row" style={{ gap: 6, fontSize: 13 }}>
            <input
              type="checkbox"
              checked={currentSummary.aiGenerated}
              disabled={currentSummary.aiModel !== null}
              onChange={(e) => {
                setCurrentSummary({ aiGenerated: e.target.checked });
                if (e.target.checked) {
                  onChange('disclosure', ensureSummaryDisclosure(form.disclosure));
                }
              }}
            />
            <span>Mark this tier as AI-drafted</span>
          </label>
        </div>
        {currentSummary.aiGenerated && (
          <div className="muted" style={{ marginTop: 8, fontSize: 13 }}>
            {AI_SUMMARY_NOTICE}
            {currentSummary.aiModel ? ` Model: ${currentSummary.aiModel}.` : ''}
          </div>
        )}
        {suggestError && <p className="error">Suggest unavailable: {suggestError}</p>}
      </div>

      <div className="row" style={{ flexWrap: 'wrap', gap: 8 }}>
        {SUMMARY_TIERS.map((tier) => {
          const draft = form.summaries[tier];
          const hasText = draft.text.trim().length > 0;
          return (
            <span
              key={tier}
              className="muted"
              style={{
                border: '1px solid var(--border)',
                borderRadius: 999,
                padding: '4px 10px',
                fontSize: 12,
                color: activeTier === tier ? 'var(--text-primary)' : undefined,
              }}
            >
              {tier}: {hasText ? (draft.aiGenerated ? 'AI' : 'draft') : 'empty'}
            </span>
          );
        })}
      </div>

      <div className="divider" />

      <div>
        <label className="field-label">AI disclosure level</label>
        <select
          className="select"
          value={form.disclosure.level}
          onChange={(e) =>
            onChange('disclosure', {
              ...form.disclosure,
              level: e.target.value as DisclosureLevel,
            })
          }
        >
          <option value="none">none — no AI assistance</option>
          <option value="assistant">assistant — grammar / phrasing only</option>
          <option value="coauthor">coauthor — AI drafted sections</option>
          <option value="primary">primary — AI is principal author</option>
        </select>
      </div>

      {form.disclosure.level !== 'none' && (
        <>
          <div>
            <label className="field-label">Where was AI used?</label>
            <div className="row" style={{ flexWrap: 'wrap', gap: 8 }}>
              {AI_USE_OPTIONS.map((opt) => (
                <button
                  key={opt}
                  type="button"
                  className="btn"
                  style={
                    form.disclosure.aiUsed.includes(opt)
                      ? { background: 'var(--accent)', color: '#0e0e10', borderColor: 'var(--accent)' }
                      : {}
                  }
                  onClick={() => toggleAiUse(opt)}
                >
                  {opt}
                </button>
              ))}
            </div>
          </div>

          <div>
            <label className="field-label">Models used (comma-separated)</label>
            <input
              className="input"
              value={form.disclosure.models}
              onChange={(e) =>
                onChange('disclosure', { ...form.disclosure, models: e.target.value })
              }
              placeholder="gemini-2.5-flash, claude-opus-4-7"
            />
          </div>

          <div>
            <label className="field-label">Notes (optional)</label>
            <textarea
              className="textarea"
              rows={3}
              value={form.disclosure.notes}
              onChange={(e) =>
                onChange('disclosure', { ...form.disclosure, notes: e.target.value })
              }
            />
          </div>
        </>
      )}

      <Nav
        onBack={onBack}
        onNext={onNext}
        nextDisabled={summaryInvalid || disclosureInvalid}
      />
    </section>
  );
}

function Step6Preview({
  form,
  intake,
  publishing,
  error,
  termsAccepted,
  onOpenTerms,
  onToggleTerms,
  onBack,
  onPublish,
}: {
  form: WizardForm;
  intake: IntakeResponse;
  publishing: boolean;
  error: string | null;
  termsAccepted: boolean;
  onOpenTerms: () => void;
  onToggleTerms: (v: boolean) => void;
  onBack: () => void;
  onPublish: () => Promise<void>;
}): JSX.Element {
  const authors = form.authors.filter((a) => a.displayName.trim());
  const summaries = buildFinalizeSummaries(form.summaries);
  return (
    <section className="stack">
      <h2 style={{ margin: 0, fontFamily: 'var(--font-serif)' }}>Preview & publish</h2>
      <article className="card">
        <h3 style={{ fontFamily: 'var(--font-serif)', margin: '0 0 8px' }}>{form.title}</h3>
        <div className="muted">{authors.map((a) => a.displayName).join(', ')}</div>
        <div className="muted">
          {form.primaryCategory}
          {form.secondaryCategories.length > 0
            ? `, ${form.secondaryCategories.join(', ')}`
            : ''}
          {' · '}
          {form.license}
        </div>
        {form.abstract && <p className="body-serif" style={{ marginTop: 12 }}>{form.abstract}</p>}
        <div className="divider" />
        <strong>Plain summaries</strong>
        <div className="stack-sm" style={{ marginTop: 8 }}>
          {summaries.map((summary) => (
            <div key={summary.tier}>
              <div className="muted" style={{ fontSize: 13, marginBottom: 4 }}>
                {summary.tier}
              </div>
              <p className="body-serif" style={{ margin: 0 }}>{summary.text}</p>
              {summary.aiGenerated && (
                <div className="muted" style={{ marginTop: 6, fontSize: 13 }}>
                  {AI_SUMMARY_NOTICE}
                  {summary.aiModel ? ` Model: ${summary.aiModel}.` : ''}
                </div>
              )}
            </div>
          ))}
        </div>
        <div className="divider" />
        <strong>AI disclosure</strong>
        <p className="muted" style={{ margin: '4px 0 0' }}>
          Level: <strong>{form.disclosure.level}</strong>
          {form.disclosure.level !== 'none' && (
            <>
              {' '}· used for: {form.disclosure.aiUsed.join(', ') || '—'} · models:{' '}
              {form.disclosure.models || '—'}
            </>
          )}
        </p>
      </article>

      {intake.previewPdfUrl && (
        <iframe
          src={intake.previewPdfUrl}
          title="PDF preview"
          style={{ width: '100%', height: 400, border: '1px solid var(--border)', borderRadius: 8, background: '#0a0a0c' }}
        />
      )}

      <article
        className="card"
        style={{
          borderColor: termsAccepted ? 'var(--tone-success)' : 'var(--border-strong)',
        }}
      >
        <div className="row" style={{ alignItems: 'flex-start', gap: 10 }}>
          <input
            id="accept-submission-terms"
            type="checkbox"
            checked={termsAccepted}
            onChange={(e) => onToggleTerms(e.target.checked)}
            disabled={publishing}
            style={{ marginTop: 3 }}
          />
          <label
            htmlFor="accept-submission-terms"
            style={{ cursor: 'pointer', flex: 1, fontSize: 14 }}
          >
            <strong>{SUBMISSION_TERMS_LABEL}</strong>
            <div className="muted" style={{ marginTop: 4, fontSize: 13 }}>
              Covers responsibility for content, what we won't host (slurs, falsified data,
              offensive language), the AI-honesty rule, what counts as unverified or
              hallucinated output, when a preprint is returned for revision vs refused outright,
              and the warranty/liability clauses.{' '}
              <button
                type="button"
                className="btn btn-ghost btn-sm"
                onClick={onOpenTerms}
                style={{ padding: '2px 8px' }}
              >
                Read the terms
              </button>
            </div>
          </label>
        </div>
      </article>

      {error && <p className="error">{error}</p>}

      <div className="row" style={{ justifyContent: 'space-between' }}>
        <button type="button" className="btn" onClick={onBack} disabled={publishing}>
          Back
        </button>
        <button
          type="button"
          className="btn btn-primary"
          onClick={onPublish}
          disabled={publishing || !termsAccepted}
          title={!termsAccepted ? 'Accept the submission terms to enable publish' : undefined}
        >
          {publishing ? 'Publishing…' : 'Publish'}
        </button>
      </div>
    </section>
  );
}

function Nav({
  onBack,
  onNext,
  nextDisabled,
}: {
  onBack: () => void;
  onNext: () => void;
  nextDisabled?: boolean;
}): JSX.Element {
  return (
    <div className="row" style={{ justifyContent: 'space-between' }}>
      <button type="button" className="btn" onClick={onBack}>
        Back
      </button>
      <button type="button" className="btn btn-primary" onClick={onNext} disabled={nextDisabled}>
        Next
      </button>
    </div>
  );
}
